import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
import * as THREE from 'three';
import {createSession} from '../lib/session.ts';
const source=await readFile(new URL('../lib/character-motion.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replace("from 'three'",`from '${import.meta.resolve('three')}'`).replace("from './session'",`from '${new URL('../lib/session.ts',import.meta.url).href}'`);
const {createCharacterMotion}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const setup=()=>{const model=new THREE.Group();const leg=new THREE.Bone();leg.name='mixamorigLeftUpLeg';model.add(leg);const clip=(name,values)=>new THREE.AnimationClip(name,1,[new THREE.QuaternionKeyframeTrack(leg.name+'.quaternion',[0,.5,1],values)]);const idle=clip('Idle',[0,0,0,1,0,0,0,1,0,0,0,1]);const run=clip('Run',[0,0,0,1,.5,0,0,.866,0,0,0,1]);return {leg,motion:createCharacterMotion(model,[idle,run]),s:createSession()};};
test('running animation continues through a coin pickup',()=>{const {leg,motion,s}=setup();s.mode='running';s.distance=1;motion.update(s,.05);const before=leg.quaternion.clone();s.mode='action';s.distance=2;motion.update(s,.05);assert.ok(before.angleTo(leg.quaternion)>.01);motion.dispose();});
test('a prompt and rest pause preserve the exact running pose',()=>{const {leg,motion,s}=setup();s.mode='running';s.distance=1;motion.update(s,.05);const before=leg.quaternion.clone();s.mode='prompt';for(let i=0;i<100;i++)motion.update(s,0);assert.deepEqual(before.toArray(),leg.quaternion.toArray());s.mode='rest';for(let i=0;i<100;i++)motion.update(s,0);assert.deepEqual(before.toArray(),leg.quaternion.toArray());motion.dispose();});
test('running keeps looping for many cycles and restarts cleanly with a new session',()=>{const {leg,motion,s}=setup();s.mode='running';for(let i=0;i<200;i++){s.distance+=.04;motion.update(s,.01);}const before=leg.quaternion.clone();s.distance+=.4;motion.update(s,.1);assert.ok(before.angleTo(leg.quaternion)>.01);s.distance=0;motion.update(s,0);const restarted=leg.quaternion.clone();s.distance=.4;motion.update(s,.1);assert.ok(restarted.angleTo(leg.quaternion)>.01);motion.dispose();});
